server:
  port: 8080
spring:
  application:
    name: blog-app
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate.ddl-auto: validate
    show-sql: ${JPA_SHOW_SQL:false}
  flyway:
    baseline-on-migrate: true