server:
  port: 8080
spring:
  application:
    name: blog-app
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate.ddl-auto: update
    show-sql: ${JPA_SHOW_SQL:true}
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation=true:

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  flyway:
    baseline-on-migrate: true

