
CREATE TABLE IF NOT EXISTS article
(
    id           int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    author_id    int8 NULL,
    body         varchar(255) NULL,
    publish_date date NULL,
    title        varchar(255) NULL,
    CONSTRAINT article_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS author
(
    id         int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 2 CACHE 1 NO CYCLE),
    age        int2 NULL,
    "password" varchar(100) NULL,
    status     varchar(255) NULL,
    username   varchar(100) NULL,
    CONSTRAINT author_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS "comment"
(
    id           int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    article_id   int8 NULL,
    author_id    int8 NULL,
    body         varchar(255) NULL,
    publish_date date NULL,
    CONSTRAINT comment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "role"
(
    id     int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    "name" varchar(255) NULL,
    CONSTRAINT role_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS author_roles
(
    author_id int8 NOT NULL,
    roles_id  int8 NOT NULL,
    CONSTRAINT author_roles_pkey PRIMARY KEY (author_id, roles_id),
    CONSTRAINT author_fk FOREIGN KEY (author_id) REFERENCES author (id),
    CONSTRAINT role_fk FOREIGN KEY (roles_id) REFERENCES "role" (id)
);